(()=>{
'use strict';
const CLIENT_ID='829151315917-8rit0pd97ol16qbnk2i141cr7gffnirb.apps.googleusercontent.com';
const SCOPE='https://www.googleapis.com/auth/calendar.events.readonly';
const TOKEN_KEY='mijnPersoonlijkeAppCalendarTokenV1';
const CONSENT_KEY='mijnPersoonlijkeAppCalendarConsentV1';
let tokenClient=null,token='',expiresAt=0,loading=false,silent=false,retried=false;
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const valid=()=>token&&expiresAt>Date.now()+30000;
function read(){try{const s=JSON.parse(localStorage.getItem(TOKEN_KEY)||'{}');if(s.token&&s.expiresAt>Date.now()+30000){token=s.token;expiresAt=s.expiresAt}else localStorage.removeItem(TOKEN_KEY)}catch{}}
function save(t,seconds){token=t||'';expiresAt=Date.now()+(Math.max(60,Number(seconds||3600)-60)*1000);try{localStorage.setItem(TOKEN_KEY,JSON.stringify({token,expiresAt}));localStorage.setItem(CONSENT_KEY,'1')}catch{}}
function clear(){token='';expiresAt=0;try{localStorage.removeItem(TOKEN_KEY)}catch{}}
function style(){if(document.getElementById('calendarIntegrationStyles'))return;const s=document.createElement('style');s.id='calendarIntegrationStyles';s.textContent='.calendar-card{padding:16px 18px}.calendar-heading{display:flex;align-items:flex-start;justify-content:space-between;gap:12px;margin-bottom:10px}.calendar-title-wrap{display:flex;align-items:center;gap:10px}.calendar-icon{width:38px;height:38px;border-radius:13px;background:var(--accent-soft);color:var(--accent-strong);display:grid;place-items:center}.calendar-card h3{margin:0 0 2px;font-size:18px}.calendar-sub,.calendar-message,.calendar-empty{color:var(--muted);font-size:12px}.calendar-list{display:grid;gap:8px}.calendar-event{display:grid;grid-template-columns:74px 1fr;gap:10px;padding:10px 11px;border:1px solid var(--line);border-radius:15px;background:var(--surface-soft)}.calendar-time{font-weight:900;color:var(--accent-strong);font-size:13px}.calendar-event-title{font-weight:800}.calendar-event-location{color:var(--muted);font-size:12px;margin-top:2px}.calendar-connect{min-height:42px;padding:9px 12px;border:0;border-radius:13px;background:var(--accent);color:#fff;font-weight:850}.calendar-refresh{width:40px;height:40px;border:0;border-radius:12px;background:var(--accent-soft);color:var(--accent-strong);font-size:19px;font-weight:900}';document.head.appendChild(s)}
const icon='<svg width="21" height="21" viewBox="0 0 24 24" fill="none"><path d="M8 3v3M16 3v3M4 9h16M6 5h12a2 2 0 0 1 2 2v11a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2V7a2 2 0 0 1 2-2Z" stroke="currentColor" stroke-width="1.9" stroke-linecap="round"/></svg>';
function ensure(){const area=document.getElementById('dayOpenArea');if(!area)return null;let card=document.getElementById('calendarTodayCard');if(!card){card=document.createElement('div');card.id='calendarTodayCard';card.className='section-card calendar-card';area.prepend(card)}render();return card}
function render(msg=''){const c=document.getElementById('calendarTodayCard');if(!c)return;if(!valid()){c.innerHTML=`<div class="calendar-heading"><div class="calendar-title-wrap"><div class="calendar-icon">${icon}</div><div><h3>Afspraken</h3><p class="calendar-sub">Google Agenda · alleen-lezen</p></div></div><button class="calendar-connect" id="calendarConnectButton">Agenda koppelen</button></div><div class="calendar-message">${esc(msg||'Agenda wordt automatisch hersteld als dat kan.')}</div>`;document.getElementById('calendarConnectButton')?.addEventListener('click',()=>request(false));return}c.innerHTML=`<div class="calendar-heading"><div class="calendar-title-wrap"><div class="calendar-icon">${icon}</div><div><h3>Afspraken</h3><p class="calendar-sub">Vandaag · alleen-lezen</p></div></div><button class="calendar-refresh" id="calendarRefreshButton">↻</button></div><div class="calendar-list" id="calendarEventList"><div class="calendar-message">Afspraken laden…</div></div>`;document.getElementById('calendarRefreshButton')?.addEventListener('click',()=>load(true))}
function gis(){if(window.google?.accounts?.oauth2)return Promise.resolve();return new Promise((ok,no)=>{const s=document.createElement('script');s.src='https://accounts.google.com/gsi/client';s.async=true;s.onload=ok;s.onerror=no;document.head.appendChild(s)})}
async function client(){await gis();if(tokenClient)return tokenClient;tokenClient=google.accounts.oauth2.initTokenClient({client_id:CLIENT_ID,scope:SCOPE,callback:r=>{const wasSilent=silent;silent=false;if(r?.error){if(!wasSilent)render('Koppelen is niet gelukt. Probeer opnieuw.');return}save(r.access_token,r.expires_in);retried=false;render();load()},error_callback:()=>{const wasSilent=silent;silent=false;if(!wasSilent)render('Google Agenda kon niet worden geopend.')}});return tokenClient}
async function request(isSilent){try{const c=await client();silent=isSilent;if(isSilent)c.requestAccessToken({prompt:''});else{let known=false;try{known=localStorage.getItem(CONSENT_KEY)==='1'}catch{}c.requestAccessToken({prompt:known?'':'consent'})}}catch{silent=false;if(!isSilent)render('Google Agenda kon niet worden gestart.')}}
function time(e){if(e?.start?.date&&!e?.start?.dateTime)return'Hele dag';if(!e?.start?.dateTime)return'';const f=new Intl.DateTimeFormat('nl-NL',{hour:'2-digit',minute:'2-digit'}),a=new Date(e.start.dateTime),b=e.end?.dateTime?new Date(e.end.dateTime):null;return b?`${f.format(a)}–${f.format(b)}`:f.format(a)}
function show(items){const list=document.getElementById('calendarEventList');if(!list)return;const v=(items||[]).filter(e=>e.status!=='cancelled');list.innerHTML=v.length?v.map(e=>`<div class="calendar-event"><div class="calendar-time">${esc(time(e))}</div><div><div class="calendar-event-title">${esc(e.summary||'Afspraak')}</div>${e.location?`<div class="calendar-event-location">${esc(e.location)}</div>`:''}</div></div>`).join(''):'<div class="calendar-empty">Geen afspraken voor vandaag.</div>'}
async function load(force=false){if(loading)return;if(!valid()){clear();if(!retried){retried=true;request(true)}else render();return}loading=true;try{const a=new Date();a.setHours(0,0,0,0);const b=new Date(a);b.setDate(b.getDate()+1);const q=new URLSearchParams({timeMin:a.toISOString(),timeMax:b.toISOString(),singleEvents:'true',orderBy:'startTime',maxResults:'25'});if(force)q.set('_',Date.now());const r=await fetch(`https://www.googleapis.com/calendar/v3/calendars/primary/events?${q}`,{headers:{Authorization:`Bearer ${token}`}});if(r.status===401||r.status===403){clear();if(!retried){retried=true;request(true)}else render('Agenda-koppeling moet opnieuw worden bevestigd.');return}if(!r.ok)throw 0;show((await r.json()).items||[])}catch{const list=document.getElementById('calendarEventList');if(list)list.innerHTML='<div class="calendar-message">Afspraken konden niet worden geladen.</div>'}finally{loading=false}}
function boot(){style();read();ensure();if(valid())load();else{retried=true;setTimeout(()=>request(true),300)}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();